export const SET_SEARCH_TRIES = "SET_SEARCH_TRIES";
export const GET_SEARCH_TRIES = "GET_SEARCH_TRIES";
export const SET_SEARCH_TRIES_SHOW = "SET_SEARCH_TRIES_SHOW";
export const GET_SEARCH_TRIES_SHOW = "GET_SEARCH_TRIES_SHOW";